name: salary-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - scikit-learn=1.4.1
  - pandas=2.2.2
  - numpy=1.26.4
  - matplotlib=3.8.4
  - seaborn=0.13.2
  - pip
  - pip:
    - mlflow==2.12.1