name: Train MLflow Model

on:
  push:
    paths:
      - '**.py'
      - 'conda.yaml'
      - 'MLProject'

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-activate-base: false
        environment-file: conda.yaml
        python-version: 3.10
        activate-environment: salary-env

    - name: Train Model with MLflow
      shell: bash -l {0}
      run: |
        mlflow run . --entry-point main -P dataset_path=ai_job_dataset.csv